### ISSUE TITLE
Support for included files

### ISSUE THREAD

**Issue by Hi-Fi** [droppedcode/typedoc-plugin-copy-assets#1]
Plugin doesn't seem to be noticing images/assets that are included in READMEs that are included with https://typedoc.org/guides/options/#includes option.

**Comment by droppedcode** [comment]
Hi Hi-Fi,

Can you please create a minimal project setup, where I can see your use case?
A git repo would be perfect.

Thanks

**Comment by Hi-Fi** [comment]
I'll try to create that, as same need is for other Typedoc plugin, too

**Comment by Hi-Fi** [comment]
Created example: https://github.com/Hi-Fi/typedoc-plugins-example

Plugin is included, and when added some console logging to plugin at node_modules it printed out only `this._reflectionPaths` as `Map(0) {}`.

Count of those logs matches to amount of markdown files, so in a way seems that included files are supported but for some reason assets are not found.

**Comment by droppedcode** [comment]
Thanks for the example.

I have fixed the issue. Previously it only looked for images, I removed this constraint.
Also added the functionality that on project reflections it will look into the typedoc current folder, I'm not sure that this always will work, but hopefully typedoc sets it to the root of the project.

So from your example it will copy the MD files and finds the main.png and others also.

Please try it and reopen issue if the solution is not enough for you.

**Comment by Hi-Fi** [comment]
Thank you, this seems to work fine (at least with example). I think that copying MD files is a bit unnecessary, as those are rendered as is and not nice looking way. 

So issue that comes being without filtering is to copy files that are not nice looking, and e.g. in multimodule setup there're also pages created that should be target, not source files. 

So in example e.g. typedoc generates pages for these two https://github.com/Hi-Fi/typedoc-plugins-example/blob/main/README.md?plain=1#L10-L11, but links point to copied assets. With replace those could be fixed, but still extra MDs are copied to docs.

**Comment by droppedcode** [comment]
Let's see you wrote one by one:

"I think that copying MD files is a bit unnecessary"
I'm not sure you added as a link so you probably want it. If you don't want it it should not be a link. The problem here that how should I know what to copy and what not.

"So issue that comes being without filtering"
I see 2 options: add and option file or add inline options to ignore something.
Options: here we could ignore by regex, but hard to do it if you want it somewhere and not in other...
Inline option:  e.g. (...)[...]?copy=false and I would remove the copy false part on parse. I'm not sure that would be ok, it can cause problems with other plugins.
Options would be the more clear option :), if you want something like this, please create a new request, with a few ideas how granular you want it and how you want to define what to keep/ignore.

"With replace those could be fixed"
With replace you can fix it. Replace plugin runs during converter section and copy assets during render section, so replace runs before the copy. This can't be changed because we need the location where to put things. For event lifecycle of typedoc see: https://www.freecodecamp.org/news/a-deep-dive-into-typedocs-workflow-and-extensibility-d464683e092c/

**Comment by Hi-Fi** [comment]
Thank you for answer, I',m really sorry if I sounded rude. 

README of plugin states image assets being the ones copied, so filtering only images sounds at least me to be enough. Not sure if there was some filtering based on extension earlier.

I can create another issue about filtering, as it would solve all things. That MD handling is something that requires another plugin to generate extra pages, but it's not problem free either. With code examples copying works better, but still misses e.g. line anchors.

Thank you also for link for the even lifecycle.

**Comment by droppedcode** [comment]
Hi @Hi-Fi, 

Sorry if it come across that I felt you were rude, there was no such issue.
I hope I could fix all issues in version 1.0.5.
