### ISSUE TITLE
typedoc@0.26 not supported

### ISSUE THREAD

**Issue by oliversalzburg** [droppedcode/typedoc-plugin-copy-assets#5]
Title pretty much sums it up

**Comment by droppedcode** [comment]
Hi @oliversalzburg,

Thank you for reporting the problem. Currently the plan is that I will archive the project, because typedoc has added this functionality with [document tag](https://typedoc.org/tags/document/).
Please check out the functionality and if there are no issues with it please use that. If for some reason it is not satisfactory please reopen the ticket and I will add the support.

See the description:
```
The @document tag can be placed in the comments for most types to add a child to that reflection in the generated documentation. The content of the @document tag should simply be a path to a markdown document to be included in the site.

/**
 * @document documents/external-markdown.md
 */
The document path is relative to the file in which the comment appears in.
```
